---
- name: configuring tomcat9
  hosts: all
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present, c: yes}
        - {a: tomcat9-admin,b: present, c: no}
    - name: copy tomcat9-users.xml file
      copy:
        src: tomcat9-users.xml
        dest: /etc/tomcat9
    - name: change port from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: pause for 1 min
      pause:
        seconds: 30
    - name: check tomcat response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.30.228:9090
        - http://172.31.21.198:9090
...

