---
- name: install jenkins in required softwares
  hosts: jenkins
  tasks:
    - name: install required softwares
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-11-jdk, b: present ,c: yes}
        - {a: git, b: present, c: no}
        - {a: maven, b: present, c: no}
    - name: download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.401.2/jenkins.war
        dest: /home/ubuntu
- name: install tomcat on QA and Prod servers
  hosts: servers
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update-cache: "{{item.c}}"
      with_items:
        - {a: tomcat9, b: present, c: yes}
        - {a: tomcat9-admin, b: present, c: no}
    - name: copy customised tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: restart tomcat9
  handlers:
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted

...          
