---
- name: configuring tomcat9
  hosts: all
  tasks:
    - name: instal tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: change port of tomcat9 from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
    - name: pause for 30 seconds
      pause:
        seconds: 30
    - name: check response from tomcat9 in node1
      uri:
        url: http://172.31.30.228:9090
        status_code: 200
    - name: check response from tomcat9 in node2
      uri:
        url: http://172.31.21.198:9090
        status_code: 200
...
